name: Main Automation

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    env:
      BRANCH_TARGET: develop
      BRANCH_MAIN: main

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive

      - name: Sync branches (main -> develop)
        uses: devmasx/merge-branch@1.4.0
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          from_branch: ${{ env.BRANCH_MAIN }}
          target_branch: ${{ env.BRANCH_TARGET }}
