name: Main Automation

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    env:
      BRANCH_TARGET: develop
      BRANCH_MAIN: main

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive

      - name: Sync branches
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          FROM_BRANCH: ${{ env.BRANCH_MAIN }}
          TO_BRANCH: ${{ env.BRANCH_TARGET }}
