name: Main Automation

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    env:
      BRANCH_TARGET: develop
      BRANCH_MAIN: main

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
          ref: ${{ env.BRANCH_TARGET }}

      - name: Merge with main branch
        run: |
          git config pull.rebase false
          git merge ${{ env.BRANCH_MAIN }}
          git push --set-upstream origin develop
